copy gui_ar.ini arabic.txt
copy gui_hy.ini armenian.txt
copy gui_az.ini azerbaijan.txt
copy gui_be.ini belarusian.txt
copy gui_pt_BR.ini brazilian.txt
copy gui_cs.ini czech.txt
copy gui_en_US.ini english.txt
copy gui_fa.ini farsi.txt
copy gui_fr.ini french.txt
copy gui_de.ini german.txt
copy gui_el.ini greek.txt
copy gui_hu.ini hungarian.txt
copy gui_it.ini italian.txt
copy gui_ja.ini japanese.txt
copy gui_lv.ini latvian.txt
copy gui_pl.ini polish.txt
copy gui_pt_PT.ini portuguese.txt
copy gui_ro.ini romanian.txt
copy gui_ru.ini russian.txt
copy gui_es.ini spanish.txt
copy gui_sv.ini swedish.txt
copy gui_tr.ini turkish.txt
copy gui_uk.ini ukrainian.txt
copy gui_nl.ini dutch.txt
copy gui_vi.ini vietnamese.txt
copy gui_bg.ini bulgarian.txt
copy gui_he.ini hebrew.txt
copy gui_lt.ini lithuanian.txt
copy gui_et.ini estonian.txt