name: SDI Lite Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y codeblocks gcc g++ xvfb libgtk-3-dev libglib2.0-dev libcairo2-dev libpango1.0-dev libatk1.0-dev

    - name: Start Xvfb
      run: |
        Xvfb :99 -screen 0 1024x768x16 &
        export DISPLAY=:99

    - name: Build SDI Lite
      run: |
        cd project
        codeblocks --rebuild --target=SDI_Lite Drivers.cbp

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: SDI Lite
        path: project/output/sdi.exe
